refact(builder): refact macos_arm64 builder

diff --git a/target_builder/macos_arm64 b/target_builder/macos_arm64
--- a/target_builder/macos_arm64
+++ b/target_builder/macos_arm64
@@ -1,135 +1,104 @@
-# Profile of macos_arm64
-
-# Do not change this plz
-rootfs_type="alpine_based"
-
-profile_name="macos_arm64"
-layer="layers/${profile_name}"
+#! /usr/bin/env bash
+if [[ $SKIP_APT_GET_INSTALL == "true" ]]; then
+	echo '$SKIP_APT_GET_INSTALL == true, skip install required package'
+else
+	sudo -E apt update && sudo -E apt -y install wget kpartx zstd || {
+		echo "Error: Install wget failed"
+		exit 100
+	}
+fi
 
 # one package one line
 preinstalled_packages="
 	bash
-	openrc
 	podman
-	e2fsprogs
-	busybox-mdev-openrc
-	busybox-openrc
 	dmesg
 	procps
 	findmnt
-	openssh-server-common-openrc
 	blkid
 	mount
-	mkinitfs
-	agetty
 	"
-# rootfs_name:download_url
-rootfs_url="
-	alpine-minirootfs-3.20.2-aarch64.tar.gz:https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/aarch64/alpine-minirootfs-3.20.2-aarch64.tar.gz
-"
-# name:download_url
-other_url=""
+rootfs_url=""
+bootable_url="https://github.com/oomol/builded/releases/download/v1.1/alpine_uefi_bootable.img.zst"
+# the alpine_uefi_bootable.img.zst has ROOTFS and EFI partition
+rootfs_part_uuid="d1e46927-eb5d-4fbf-986a-7e5581f37a16"
+efi_part_uuid="6729-82AB"
 
 # file_name:sha1sum
-sha1sum="
-	alpine-minirootfs-3.20.2-aarch64.tar.gz:62f6c6cdf6a5a1f1d45f4d4458c7e59839997f78
-"
+sha1sum="8eafdf68d20b327382a4a7fbd873803e49287b75  alpine_uefi_bootable.img.zst"
 
+bootstrap_alpine() {
+	rm -rf "$output/alpine_uefi_bootable.img.zst"
+	wget -c "$bootable_url" --output-document="$output/alpine_uefi_bootable.img.zst"
+	echo "$sha1sum" >$output/alpine_uefi_bootable.img.zst.sha1sum
 
-# Build kernel for macos_arm64 using custom kernel config
-kernel_builder() {
-	echo "Build kernel for $profile_name"
-	if [[ ! -n ${workspace} ]]; then
-		echo 'Error: env ${workspace} empty'
+	cd $output && sha1sum -c alpine_uefi_bootable.img.zst.sha1sum || {
+		echo "Error: checksha1sum failed"
 		exit 100
-	else
-		cd $workspace
-	fi
-	if [[ ! -n ${output} ]]; then
-		echo 'Error: env ${output} empty'
-		exit 100
-	fi
+	} && cd $workspace
 
-	set -x
-	kernel_config="${workspace}/layers/macos_arm64/etc/buildinfo/kernel_config"
-	set +x
-	if [[ -f ${kernel_config} ]]; then
-		set -x
-		# CLEAN_BUILD false to cache build result
-		CLEAN_BUILD=false \
-			PULL_SOURCE_BUILD=true \
-			N_PROC=16 \
-			WORKSPACE=${workspace} \
-			./subfunc/build_kernel.sh \
-			next \
-			rockchip/rk3399-eaidk-610 ${kernel_config} ${output}
-			set +x
-	else
-		echo 'Error: env ${kernel_config}'
-		exit 100
-	fi
-	export KERNEL_BUILDED=true
+	cd $output && {
+		# Decompress alpine_uefi_bootable.img.zst
+		zstd -d -f alpine_uefi_bootable.img.zst || {
+			echo "Decompress alpine_uefi_bootable.img.zst failed"
+			exit 100
+		}
+		# Mapping the part into /dev/mapper/loopNpN
+		kpartx -av alpine_uefi_bootable.img &&
+			mount -m -U $rootfs_part_uuid ./target_rootfs &&
+			mount -m -U $efi_part_uuid ./target_rootfs/boot/efi || {
+			echo "Error: Mount alpine_uefi_bootable.img failed"
+			exit 100
+		}
+	} && cd $workspace
+
+	cd $output && {
+		# Podman live in http://dl-cdn.alpinelinux.org/alpine/v3.20/community
+		echo http://dl-cdn.alpinelinux.org/alpine/v3.20/community >>target_rootfs/etc/apk/repositories
+	} && cd $workspace
+
+	# Install required package into rootfs
+	cd $output && {
+		pkgs=$(echo $preinstalled_packages | xargs)
+		if [[ $NATIVE_BUILD == true ]]; then
+			set -x
+			sudo -E proot --rootfs=./target_rootfs \
+				-b /dev:/dev \
+				-b /sys:/sys \
+				-b /proc:/proc \
+				-b /etc/resolv.conf:/etc/resolv.conf \
+				-w /root \
+				-0 /bin/su -c "apk update;apk add $pkgs" || {
+				set +x
+				echo "Error: proot into rootfs failed"
+				exit 100
+			}
+		else
+			set -x
+			sudo -E proot --qemu=qemu-x86_64-static --rootfs=./target_rootfs \
+				-b /dev:/dev \
+				-b /sys:/sys \
+				-b /proc:/proc \
+				-b /etc/resolv.conf:/etc/resolv.conf \
+				-w /root \
+				-0 /bin/su -c "apk update;apk add $pkgs" || {
+				set +x
+				echo "Error: proot into rootfs failed"
+				exit 100
+			}
+		fi
+	} && cd $workspace
+	sync
 }
 
-# intended_func will be called in make, do not change this function name.
-intended_func() {
-	# Nothing todo
-	echo -n "intended_func in $profile_name"
-	if [[ -f ${proot_src}/src/proot ]];then
-		echo -n ""
-	else
-		echo 'Error: ${proot_src}/src/proot not exist'
-		exit 100
-	fi
-	# Enable necessary rc-services
-	if [[ -n ${rootfs_path} ]]; then
-		set -x
-		sudo -E ${proot_src}/src/proot --rootfs=${rootfs_path} \
-			-b /dev:/dev \
-			-b /sys:/sys \
-			-b /proc:/proc \
-			-b /etc/resolv.conf:/etc/resolv.conf \
-			-w /root \
-			-0 /bin/su -c "
-rc-update add acpid default
-rc-update add bootmisc boot
-rc-update add crond default
-rc-update add devfs sysinit
-rc-update add dmesg sysinit
-rc-update add hostname boot
-rc-update add hwclock boot
-rc-update add hwdrivers sysinit
-rc-update add killprocs shutdown
-rc-update add mdev sysinit
-rc-update add modules boot
-rc-update add mount-ro shutdown
-rc-update add networking boot
-rc-update add savecache shutdown
-rc-update add seedrng boot
-rc-update add swap boot
-			"
-		set +x
-	else
-		echo 'env ${rootfs_path} empty'
-		exit 100
-	fi
+echo "=== Bootstrap Alpine ==="
+if [[ -z $workspace ]] && [[ -z $output ]]; then
+	echo 'Error: $workspace or $output empty'
+	exit 100
+fi
 
-	# Copy interfaces configure into rootfs, the lo should be autoconfig
-	if [[ -n ${rootfs_path} ]]; then
-		cd $_cwd_
-		cp layers/macos_arm64/etc/network/interfaces ${rootfs_path}/etc/network/interfaces
-	fi
-	export ROOTFS_BUILDED=true
-}
-
-make_rootfs_disk(){
-	if [[  $KERNEL_BUILDED != true ]];then
-		echo "Error: Kernel not build..."
-		echo "not make rootfs disk"
-	fi
-	if [[  $ROOTFS_BUILDED != true ]];then
-		echo "Error: rootfs not build..."
-		echo "not make rootfs disk"
-	fi
-	SIZE=4G  ./subfunc/mkext4disk.sh 
-}
+echo workspace: $workspace
+echo output: $output
+bootstrap_alpine
+#copy_layer
+#pack_rootfs
