refact(builder): add ovmservice into default stage

diff --git a/target_builder/macos_arm64 b/target_builder/macos_arm64
--- a/target_builder/macos_arm64
+++ b/target_builder/macos_arm64
@@ -128,7 +128,29 @@ copy_layer() {
 		echo 'Error: change dir to ./layers/$target_profile failed'
 		exit 100
 	} && cd $workspace
+
+	cd $output && {
+		sudo -E proot $qemu_flag --rootfs=./target_rootfs \
+			-b /dev:/dev \
+			-b /sys:/sys \
+			-b /proc:/proc \
+			-b /etc/resolv.conf:/etc/resolv.conf \
+			-w /root \
+			-0 /bin/su -c "chmod +x /etc/init.d/ovmservice ; rc-update add ovmservice default" || {
+			echo "Error: add ovmservice into default stage failed"
+			exit 100
+		}
+	} && cd $workspace
+
+	cd $output && {
+		umount -R ./target_rootfs
+	} || {
+		echo "Error: failed to umount $output/target_rootfs"
+		exit 100
+	} && cd $workspace
+
 	set +x
+	sync # must do sync !
 }
 
 pack_rootfs() {
