refact(builder): refact install_qemu.sh support both arm64 and x86_64

diff --git a/target_builder/macos_amd64 b/target_builder/macos_amd64
--- a/target_builder/macos_amd64
+++ b/target_builder/macos_amd64
@@ -213,6 +213,17 @@ pack_rootfs() {
 	set +x
 }
 
+bootimage() {
+	cd "$workspace" || {
+		echo "Failed to change dir to workspace"
+		exit 100
+	}
+	bash +x ./subfunc/boot_raw_disk.sh "$output/$bootable_file" x86_64 && {
+		echo "Error: boot $output/$bootable_file failed"
+		exit 100
+	}
+}
+
 echo "=== Bootstrap Alpine ==="
 if [[ -z $workspace ]] && [[ -z $output ]]; then
 	echo 'Error: $workspace or $output empty'
@@ -226,3 +237,4 @@ bootstrap_alpine
 #copy_layer
 pack_rootfs
 clean_mapping
+#bootimage
